name: Windows Runtime

on:
  push:
    branches:
      test-build

jobs:
  runtime-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive --depth 1
    - name: Get Node.js
      run: git clone https://github.com/Kode/nodejs_bin.git --depth 1
    - name: Compile
      run: .\nodejs_bin\node.exe Kha/make -g opengl --compile
    - name: Procure results
      uses: actions/upload-artifact@v3
      with:
        name: runtime-windows
        path: build/windows

  exporter-windows:
    runs-on: windows-latest
    needs: runtime-windows
    steps:
    - uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install exporter deps
      run: pip install -r requirements.txt
    - name: Install PyInstaller
      run: pip install -U pyinstaller
    - name: Download runtime
      uses: actions/download-artifact@v3
      with:
        name: runtime-windows
        path: build/windows
    - name: Create PyInstaller distribution
      run: pyinstaller.exe mouse.py -w --workpath pybuild --add-data "build;build" --add-data "tools;tools" --icon icon.png
    - name: Procure results
      uses: actions/upload-artifact@v3
      with:
        name: runtime-windows
        path: dist
    
    
